services:
  aria2:
    container_name: aria2-pro
    image: p3terx/aria2-pro:latest
    volumes:
      - ${DOWNLOAD_DIR}:/downloads
      - ./config:/config
    # ports:
    #   - "6800:6800"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Seoul
    restart: unless-stopped
    networks:
      - proxy
    env_file:
      - "./rpc.env"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.aria2.entrypoints=websecure"
      - "traefik.http.routers.aria2.rule=Host(`${TRF_DOMAIN}`) && PathPrefix(`/aria2`)"
      - "traefik.http.routers.aria2.tls=true"
      - "traefik.http.routers.aria2.tls.certresolver=leresolver"
      - "traefik.http.routers.aria2.middlewares=aria2-stripprefix"
      - "traefik.http.services.aria2.loadbalancer.server.port=6800"
      # - "traefik.http.services.aria2.loadbalancer.server.scheme=https"
      - "traefik.http.middlewares.aria2-stripprefix.stripprefix.prefixes=/aria2"

  # AriaNg is just a static web page, usually you only need to deploy on a single host.
  ariang:
    container_name: ariang
    build: ./AriaNg
    # network_mode: host
    #    ports:
    #      - 6880:6880
    restart: unless-stopped
    # logging:
    # driver: json-file
    # options:
    # max-size: 1m
    volumes:
      - ./AriaNg/nginx.conf:/etc/nginx/nginx.conf/:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.ariang.entrypoints=websecure"
      - "traefik.http.routers.ariang.rule=Host(`${TRF_DOMAIN}`) && PathPrefix(`/ariang`)"
      - "traefik.http.routers.ariang.tls=true"
      - "traefik.http.routers.ariang.tls.certresolver=leresolver"
      - "traefik.http.routers.ariang.middlewares=ariang-stripprefix"
      - "traefik.http.services.ariang.loadbalancer.server.port=80"
      # - "traefik.http.services.ariang.loadbalancer.server.scheme=https"
      - "traefik.http.middlewares.ariang-stripprefix.stripprefix.prefixes=/ariang"
    networks:
      - proxy

networks:
  proxy:
    external: true
