services:
  app:
    build: .
    restart: always
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    volumes:
      - ${DATA_PATH}/main:/var/www/html
      - ${MEDIA_PATH}:/media
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    networks:
      - back
      - db
    depends_on:
      - db
      - redis

  web:
    image: nginx:1.23.2-alpine
    restart: always
    volumes:
      - ${DATA_PATH}/main:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - front
      - back
    depends_on:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=front"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_DOMAIN}`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=leresolver"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-regex"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=9999"
      # - "traefik.http.middlewares.nextcloud-buffering.buffering.memRequestBodyBytes=10477568"
      # - "traefik.http.middlewares.nextcloud-buffering.buffering.memResponseBodyBytes=10477568"
      - "traefik.http.middlewares.nextcloud-regex.redirectRegex.permanent=true"
      - "traefik.http.middlewares.nextcloud-regex.redirectRegex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-regex.redirectRegex.replacement=https://$$1/remote.php/dav/"

  cron:
    image: nextcloud:stable-fpm-alpine
    restart: always
    volumes:
      - ${DATA_PATH}/main:/var/www/html
    entrypoint: /cron.sh
    networks:
      - back
    depends_on:
      - app

  db:
    image: postgres:alpine
    restart: always
    volumes: 
      - "${DATA_PATH}/db:/var/lib/postgresql/data"
    env_file:
      - db.env
    networks:
      - db
  
  redis:
    image: redis:alpine
    restart: always
    networks:
      - db

networks:
  back:
    external: false
  db:
    external: false
  front:
    external: true


